---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Packages:
library(stringr)
library(knitr)
```



```{r load}
#Load the raw data
rawData<-read.csv("Week 3/Raw Data/Week 3 Example Data.csv")


#Create a copy of the raw data to trace back and compare
data<-rawData
```




```{r restructure}

colnames(data)[6:15]<-paste0("tipi",
                          rep(c("E","A","C","N","O"),2),
                          1:10)

#Append an R to reverse coded items
colnames(data)[c(7,11,13:15)]<-paste0(colnames(data)[c(7,11,13:15)],"R")


###Restructure variables###


#Split the condition variable into two columns
conditionSplit<-str_split_fixed(data$condition,"_",2)


#Rename the newly conditioned variables
colnames(conditionSplit)<-c("shockCause","pMoral")

#Add the split columns back to the data
data<-cbind(data,conditionSplit)

data<-data[,-4]

data$guilt<-ifelse(data$guilt==-99,NA,data$guilt)

```




```{r compute}

data[,c(6,10,12:14)]<-(-1*data[,c(6,10,12:14)])+8


#compute composite personality scores
data$extra<-rowMeans(data[,c(5,10)])

data$extra<-rowMeans(data[,c(5,10)])
data$agree<-rowMeans(data[,c(6,11)])
data$consc<-rowMeans(data[,c(7,12)])
data$neuro<-rowMeans(data[,c(8,13)])
data$open<-rowMeans(data[,c(9,14)])
```




```{r codebook}
#Rearrange
data<-data[,c(1:3,5:14,20:24,4,18:19,15:17)]

codebook<-data.frame("variable"=colnames(data))

codebook$description<-c(
  "Participant ID Number",
  "Participant Sex",
  "Age",
  "TIPI Extraversion 1",
  "TIPI Agreeableness 1 (R)",
  "TIPI Conscientiousness 1",
  "TIPI Neuroticism 1",
  "TIPI Openness 1",
  "TIPI Extraversion 2 (R)",
  "TIPI Agreeableness 2",
  "TIPI Conscientiousness 2 (R)",
  "TIPI Neuroticism 2 (R)",
  "TIPI Openness 2 (R)",
  "Composite Extraversion",
  "Composite Agreeableness",
  "Composite Conscientiousness",
  "Composite Neuroticism",
  "Composite Openness",
  "Shock Voltage",
  "Shock Cause (participant vs. partner)",
  "Partner Morality (good vs. bad)",
  "Amount of $ Shared with Partner (pre-shock)",
  "Amount of $ Shared with Partner (post-shock)",
  "Guilt"
  

)

#Save the data type for each variable
codebook$type<-sapply(data,class)

#Output the codebook as a table
kable(codebook)
```




```{r save}

#Save the Data
write.csv(data,"Week 3/Processed Data/Week 3 Data PROCESSED.csv")

```
25/500

